-- テーブル作成
CREATE TABLE `countries` (
	`id`       
		INT NOT NULL AUTO_INCREMENT
		COMMENT '識別番号' ,
    	
	`code_2` 
		CHAR(2) CHARACTER SET ascii NOT NULL 
		COMMENT '国コード(2桁数字)' ,
    
	`code_3` 
		CHAR(3) CHARACTER SET ascii NOT NULL 
		COMMENT '国コード(3桁数字)' ,
    
	`code` 
		CHAR(3) CHARACTER SET ascii NOT NULL 
		COMMENT '国コード(3桁英字)' ,
    	
	`name` 
		VARCHAR(50) NOT NULL
		COMMENT '国名',
		
	PRIMARY KEY (`id`)
);

-- キー
ALTER TABLE `countries` ADD UNIQUE KEY `countries_code`   USING HASH (`code`);
ALTER TABLE `countries` ADD UNIQUE KEY `countries_code_2` USING HASH (`code_2`);
ALTER TABLE `countries` ADD UNIQUE KEY `countries_code_3` USING HASH (`code_3`);

-- 初期データ投入
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IS', 'ISL', '352', 'アイスランド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IE', 'IRL', '372', 'アイルランド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AZ', 'AZE', '031', 'アゼルバイジャン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AF', 'AFG', '004', 'アフガニスタン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('US', 'USA', '840', 'アメリカ合衆国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AS', 'ASM', '016', 'アメリカ領サモア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VI', 'VIR', '850', 'アメリカ領バージン諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AE', 'ARE', '784', 'アラブ首長国連邦');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('DZ', 'DZA', '012', 'アルジェリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AR', 'ARG', '032', 'アルゼンチン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AW', 'ABW', '533', 'アルバ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AL', 'ALB', '008', 'アルバニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AM', 'ARM', '051', 'アルメニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AI', 'AIA', '660', 'アンギラ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AO', 'AGO', '024', 'アンゴラ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AG', 'ATG', '028', 'アンティグア・バーブーダ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AD', 'AND', '020', 'アンドラ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('YE', 'YEM', '887', 'イエメン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GB', 'GBR', '826', 'イギリス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IO', 'IOT', '086', 'イギリス領インド洋地域');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VG', 'VGB', '092', 'イギリス領バージン諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IL', 'ISR', '376', 'イスラエル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IT', 'ITA', '380', 'イタリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IQ', 'IRQ', '368', 'イラク');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IR', 'IRN', '364', 'イラン・イスラム共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IN', 'IND', '356', 'インド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ID', 'IDN', '360', 'インドネシア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('UG', 'UGA', '800', 'ウガンダ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('UA', 'UKR', '804', 'ウクライナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('UZ', 'UZB', '860', 'ウズベキスタン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('UY', 'URY', '858', 'ウルグアイ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('EC', 'ECU', '218', 'エクアドル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('EG', 'EGY', '818', 'エジプト');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('EE', 'EST', '233', 'エストニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SZ', 'SWZ', '748', 'エスワティニ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ET', 'ETH', '231', 'エチオピア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ER', 'ERI', '232', 'エリトリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SV', 'SLV', '222', 'エルサルバドル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AU', 'AUS', '036', 'オーストラリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AT', 'AUT', '040', 'オーストリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AX', 'ALA', '248', 'オーランド諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('OM', 'OMN', '512', 'オマーン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NL', 'NLD', '528', 'オランダ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GH', 'GHA', '288', 'ガーナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GG', 'GGY', '831', 'ガーンジー島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GY', 'GUY', '328', 'ガイアナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KZ', 'KAZ', '398', 'カザフスタン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('QA', 'QAT', '634', 'カタール');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('UM', 'UMI', '581', '合衆国領有小離島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CA', 'CAN', '124', 'カナダ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CV', 'CPV', '132', 'カボベルデ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GA', 'GAB', '266', 'ガボン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CM', 'CMR', '120', 'カメルーン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GM', 'GMB', '270', 'ガンビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KH', 'KHM', '116', 'カンボジア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MK', 'MKD', '807', ' 北マケドニア共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MP', 'MNP', '580', '北マリアナ諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GN', 'GIN', '324', 'ギニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GW', 'GNB', '624', 'ギニアビサウ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CY', 'CYP', '196', 'キプロス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CU', 'CUB', '192', 'キューバ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CW', 'CUW', '531', 'キュラソー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GR', 'GRC', '300', 'ギリシャ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KI', 'KIR', '296', 'キリバス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KG', 'KGZ', '417', 'キルギス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GT', 'GTM', '320', 'グアテマラ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GP', 'GLP', '312', 'グアドループ島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GU', 'GUM', '316', 'グアム');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KW', 'KWT', '414', 'クウェート');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CK', 'COK', '184', 'クック諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GL', 'GRL', '304', 'グリーンランド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CX', 'CXR', '162', 'クリスマス島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GD', 'GRD', '308', 'グレナダ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('HR', 'HRV', '191', 'クロアチア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KY', 'CYM', '136', 'ケイマン諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KE', 'KEN', '404', 'ケニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CI', 'CIV', '384', 'コートジボワール');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CC', 'CCK', '166', 'ココス（キーリング）諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CR', 'CRI', '188', 'コスタリカ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KM', 'COM', '174', 'コモロ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CO', 'COL', '170', 'コロンビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CG', 'COG', '178', 'コンゴ共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CD', 'COD', '180', 'コンゴ民主共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SA', 'SAU', '682', 'サウジアラビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GS', 'SGS', '239', 'サウスジョージア・サウスサンドウィッチ諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('WS', 'WSM', '882', 'サモア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ST', 'STP', '678', 'サントメ・プリンシペ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BL', 'BLM', '652', 'サン・バルテルミー島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ZM', 'ZMB', '894', 'ザンビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PM', 'SPM', '666', 'サンピエール・ミクロン島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SM', 'SMR', '674', 'サンマリノ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MF', 'MAF', '663', 'サン・マルタン島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SL', 'SLE', '694', 'シエラレオネ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('DJ', 'DJI', '262', 'ジブチ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GI', 'GIB', '292', 'ジブラルタル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('JE', 'JEY', '832', 'ジャージー島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('JM', 'JAM', '388', 'ジャマイカ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GE', 'GEO', '268', 'ジョージア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SY', 'SYR', '760', 'シリア・アラブ共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SG', 'SGP', '702', 'シンガポール');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SX', 'SXM', '534', 'シント・マールテン（オランダ領）');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ZW', 'ZWE', '716', 'ジンバブエ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CH', 'CHE', '756', 'スイス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SE', 'SWE', '752', 'スウェーデン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SD', 'SDN', '729', 'スーダン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SJ', 'SJM', '744', 'スバールバル諸島・ヤンマイエン島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ES', 'ESP', '724', 'スペイン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SR', 'SUR', '740', 'スリナム');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LK', 'LKA', '144', 'スリランカ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SK', 'SVK', '703', 'スロバキア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SI', 'SVN', '705', 'スロベニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SC', 'SYC', '690', 'セーシェル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GQ', 'GNQ', '226', '赤道ギニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SN', 'SEN', '686', 'セネガル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('RS', 'SRB', '688', 'セルビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KN', 'KNA', '659', 'セントクリストファー・ネビス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VC', 'VCT', '670', 'セントビンセント・グレナディーン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SH', 'SHN', '654', 'セントヘレナ・アセンションおよびトリスタンダクーニャ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LC', 'LCA', '662', 'セントルシア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SO', 'SOM', '706', 'ソマリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SB', 'SLB', '090', 'ソロモン諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TC', 'TCA', '796', 'タークスカイコス諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TH', 'THA', '764', 'タイ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KR', 'KOR', '410', '大韓民国 (韓国)');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TW', 'TWN', '158', '台湾');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TJ', 'TJK', '762', 'タジキスタン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TZ', 'TZA', '834', 'タンザニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CZ', 'CZE', '203', 'チェコ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TD', 'TCD', '148', 'チャド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CF', 'CAF', '140', '中央アフリカ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CN', 'CHN', '156', '中華人民共和国 (中国)');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TN', 'TUN', '788', 'チュニジア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('KP', 'PRK', '408', '朝鮮民主主義人民共和国 (北朝鮮)');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('CL', 'CHL', '152', 'チリ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TV', 'TUV', '798', 'ツバル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('DK', 'DNK', '208', 'デンマーク');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('DE', 'DEU', '276', 'ドイツ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TG', 'TGO', '768', 'トーゴ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TK', 'TKL', '772', 'トケラウ諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('DO', 'DOM', '214', 'ドミニカ共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('DM', 'DMA', '212', 'ドミニカ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TT', 'TTO', '780', 'トリニダード・トバゴ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TM', 'TKM', '795', 'トルクメニスタン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TR', 'TUR', '792', 'トルコ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TO', 'TON', '776', 'トンガ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NG', 'NGA', '566', 'ナイジェリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NR', 'NRU', '520', 'ナウル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NA', 'NAM', '516', 'ナミビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('AQ', 'ATA', '010', '南極');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NU', 'NIU', '570', 'ニウエ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NI', 'NIC', '558', 'ニカラグア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NE', 'NER', '562', 'ニジェール');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('JP', 'JPN', '392', '日本');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('EH', 'ESH', '732', '西サハラ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NC', 'NCL', '540', 'ニューカレドニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NZ', 'NZL', '554', 'ニュージーランド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NP', 'NPL', '524', 'ネパール');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NF', 'NFK', '574', 'ノーフォーク島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('NO', 'NOR', '578', 'ノルウェー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('HM', 'HMD', '334', 'ハード島・マクドナルド諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BH', 'BHR', '048', 'バーレーン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('HT', 'HTI', '332', 'ハイチ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PK', 'PAK', '586', 'パキスタン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VA', 'VAT', '336', 'バチカン市国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PA', 'PAN', '591', 'パナマ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VU', 'VUT', '548', 'バヌアツ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BS', 'BHS', '044', 'バハマ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PG', 'PNG', '598', 'パプアニューギニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BM', 'BMU', '060', 'バミューダ諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PW', 'PLW', '585', 'パラオ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PY', 'PRY', '600', 'パラグアイ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BB', 'BRB', '052', 'バルバドス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PS', 'PSE', '275', 'パレスチナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('HU', 'HUN', '348', 'ハンガリー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BD', 'BGD', '050', 'バングラデシュ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TL', 'TLS', '626', '東ティモール');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PN', 'PCN', '612', 'ピトケアン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('FJ', 'FJI', '242', 'フィジー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PH', 'PHL', '608', 'フィリピン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('FI', 'FIN', '246', 'フィンランド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BT', 'BTN', '064', 'ブータン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BV', 'BVT', '074', 'ブーベ島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PR', 'PRI', '630', 'プエルトリコ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('FO', 'FRO', '234', 'フェロー諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('FK', 'FLK', '238', 'フォークランド（マルビナス）諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BR', 'BRA', '076', 'ブラジル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('FR', 'FRA', '250', 'フランス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('GF', 'GUF', '254', 'フランス領ギアナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PF', 'PYF', '258', 'フランス領ポリネシア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('TF', 'ATF', '260', 'フランス領南方・南極地域');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BG', 'BGR', '100', 'ブルガリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BF', 'BFA', '854', 'ブルキナファソ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BN', 'BRN', '096', 'ブルネイ・ダルサラーム');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BI', 'BDI', '108', 'ブルンジ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VN', 'VNM', '704', 'ベトナム');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BJ', 'BEN', '204', 'ベナン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('VE', 'VEN', '862', 'ベネズエラ・ボリバル共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BY', 'BLR', '112', 'ベラルーシ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BZ', 'BLZ', '084', 'ベリーズ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PE', 'PER', '604', 'ペルー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BE', 'BEL', '056', 'ベルギー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PL', 'POL', '616', 'ポーランド');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BA', 'BIH', '070', 'ボスニア・ヘルツェゴビナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BW', 'BWA', '072', 'ボツワナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BQ', 'BES', '535', 'ボネール、シント・ユースタティウスおよびサバ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('BO', 'BOL', '068', 'ボリビア多民族国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('PT', 'PRT', '620', 'ポルトガル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('HK', 'HKG', '344', '香港');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('HN', 'HND', '340', 'ホンジュラス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MH', 'MHL', '584', 'マーシャル諸島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MO', 'MAC', '446', 'マカオ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MG', 'MDG', '450', 'マダガスカル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('YT', 'MYT', '175', 'マヨット島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MW', 'MWI', '454', 'マラウイ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ML', 'MLI', '466', 'マリ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MT', 'MLT', '470', 'マルタ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MQ', 'MTQ', '474', 'マルティニク');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MY', 'MYS', '458', 'マレーシア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('IM', 'IMN', '833', 'マン島');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('FM', 'FSM', '583', 'ミクロネシア連邦');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ZA', 'ZAF', '710', '南アフリカ共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('SS', 'SSD', '728', '南スーダン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MM', 'MMR', '104', 'ミャンマー');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MX', 'MEX', '484', 'メキシコ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MU', 'MUS', '480', 'モーリシャス');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MR', 'MRT', '478', 'モーリタニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MZ', 'MOZ', '508', 'モザンビーク');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MC', 'MCO', '492', 'モナコ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MV', 'MDV', '462', 'モルディブ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MD', 'MDA', '498', 'モルドバ共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MA', 'MAR', '504', 'モロッコ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MN', 'MNG', '496', 'モンゴル');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ME', 'MNE', '499', 'モンテネグロ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('MS', 'MSR', '500', 'モントセラト');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('JO', 'JOR', '400', 'ヨルダン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LA', 'LAO', '418', 'ラオス人民民主共和国');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LV', 'LVA', '428', 'ラトビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LT', 'LTU', '440', 'リトアニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LY', 'LBY', '434', 'リビア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LI', 'LIE', '438', 'リヒテンシュタイン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LR', 'LBR', '430', 'リベリア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('RO', 'ROU', '642', 'ルーマニア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LU', 'LUX', '442', 'ルクセンブルク');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('RW', 'RWA', '646', 'ルワンダ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LS', 'LSO', '426', 'レソト');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('LB', 'LBN', '422', 'レバノン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('RE', 'REU', '638', 'レユニオン');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('RU', 'RUS', '643', 'ロシア');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('WF', 'WLF', '876', 'ワリスフュチュナ');
INSERT INTO `countries` (`code_2`,`code_3`,`code`,`name`) VALUES ('ZZ', 'ZZZ', '999', 'その他');
